{
  "openapi": "3.0.1",
  "info": {
    "title": "todo-rest",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://apim-xekb7t6tcr2zo.azure-api.net/todo-rest"
    }
  ],
  "paths": {
    "/todo/lists": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists - GET",
        "operationId": "get-todo-lists",
        "parameters": [
          {
            "name": "$skip",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "$top",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoListDtoPage"
                },
                "example": {
                  "items": [
                    {
                      "id": "string",
                      "name": "string",
                      "description": "string",
                      "createdDate": "string",
                      "updatedDate": "string"
                    }
                  ],
                  "hasMoreItems": true,
                  "nextLink": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists - POST",
        "operationId": "post-todo-lists",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoListDto"
                },
                "example": {
                  "id": "string",
                  "name": "string",
                  "description": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          }
        }
      }
    },
    "/todo/lists/{list_id}": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id} - GET",
        "operationId": "get-todo-lists-list_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoListDto"
                },
                "example": {
                  "id": "string",
                  "name": "string",
                  "description": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id} - PUT",
        "operationId": "put-todo-lists-list_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoList"
              },
              "example": {
                "name": "string",
                "description": "string"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoListDto"
                },
                "example": {
                  "id": "string",
                  "name": "string",
                  "description": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id} - DELETE",
        "operationId": "delete-todo-lists-list_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      }
    },
    "/todo/lists/{list_id}/items": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/items - GET",
        "operationId": "get-todo-lists-list_id-items",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "$skip",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "$top",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDtoPage"
                },
                "example": {
                  "items": [
                    {
                      "id": "string",
                      "listId": "string",
                      "name": "string",
                      "description": "string",
                      "state": "todo",
                      "dueDate": "string",
                      "completedDate": "string",
                      "createdDate": "string",
                      "updatedDate": "string"
                    }
                  ],
                  "hasMoreItems": true,
                  "nextLink": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/items - POST",
        "operationId": "post-todo-lists-list_id-items",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDto"
                },
                "example": {
                  "id": "string",
                  "listId": "string",
                  "name": "string",
                  "description": "string",
                  "state": "todo",
                  "dueDate": "string",
                  "completedDate": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      }
    },
    "/todo/lists/{list_id}/items/{item_id}": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/items/{item_id} - GET",
        "operationId": "get-todo-lists-list_id-items-item_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "item_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDto"
                },
                "example": {
                  "id": "string",
                  "listId": "string",
                  "name": "string",
                  "description": "string",
                  "state": "todo",
                  "dueDate": "string",
                  "completedDate": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/items/{item_id} - PUT",
        "operationId": "put-todo-lists-list_id-items-item_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "item_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUpdateTodoItem"
              },
              "example": {
                "name": "string",
                "state": "string",
                "dueDate": "string",
                "completedDate": "string",
                "description": "string"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDto"
                },
                "example": {
                  "id": "string",
                  "listId": "string",
                  "name": "string",
                  "description": "string",
                  "state": "todo",
                  "dueDate": "string",
                  "completedDate": "string",
                  "createdDate": "string",
                  "updatedDate": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/items/{item_id} - DELETE",
        "operationId": "delete-todo-lists-list_id-items-item_id",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "item_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "default": {
                    "value": null
                  }
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      }
    },
    "/todo/lists/{list_id}/state/{state}": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "/todo/lists/{list_id}/state/{state} - GET",
        "operationId": "get-todo-lists-list_id-state-state",
        "parameters": [
          {
            "name": "list_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "state",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "$skip",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "$top",
            "in": "query",
            "description": "Format - int32.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TodoItemDtoPage"
                },
                "example": {
                  "items": [
                    {
                      "id": "string",
                      "listId": "string",
                      "name": "string",
                      "description": "string",
                      "state": "todo",
                      "dueDate": "string",
                      "completedDate": "string",
                      "createdDate": "string",
                      "updatedDate": "string"
                    }
                  ],
                  "hasMoreItems": true,
                  "nextLink": "string"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                },
                "example": {
                  "type": "string",
                  "title": "string",
                  "status": 0,
                  "detail": "string",
                  "instance": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateUpdateTodoItem": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "state": {
            "type": "string",
            "nullable": true
          },
          "dueDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "completedDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "CreateUpdateTodoList": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": { }
      },
      "TodoItemDto": {
        "required": [
          "createdDate",
          "id",
          "listId",
          "name",
          "state",
          "updatedDate"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "listId": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "state": {
            "$ref": "#/components/schemas/TodoItemState"
          },
          "dueDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "completedDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          },
          "updatedDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "TodoItemDtoPage": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TodoItemDto"
            },
            "nullable": true
          },
          "hasMoreItems": {
            "type": "boolean"
          },
          "nextLink": {
            "type": "string",
            "format": "uri",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "TodoItemState": {
        "enum": [
          "todo",
          "inProgress",
          "done"
        ],
        "type": "string"
      },
      "TodoListDto": {
        "required": [
          "createdDate",
          "id",
          "name",
          "updatedDate"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "createdDate": {
            "type": "string",
            "format": "date-time"
          },
          "updatedDate": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "TodoListDtoPage": {
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TodoListDto"
            },
            "nullable": true
          },
          "hasMoreItems": {
            "type": "boolean"
          },
          "nextLink": {
            "type": "string",
            "format": "uri",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "apiKeyHeader": {
        "type": "apiKey",
        "name": "Ocp-Apim-Subscription-Key",
        "in": "header"
      },
      "apiKeyQuery": {
        "type": "apiKey",
        "name": "subscription-key",
        "in": "query"
      }
    }
  },
  "security": [
    {
      "apiKeyHeader": [ ]
    },
    {
      "apiKeyQuery": [ ]
    }
  ]
}